### ISSUE TITLE
docker scout quickview crashes if an image is not specified

### ISSUE THREAD

**Issue by norman-abramovitz** [docker/scout-cli#125]
The quickview crashes if you do not specify an image.

docker scout version
version: v1.9.3 (go1.22.3 - darwin/arm64)
git commit: e3dbad31cfc7736809470453fc317c22d361c207

docker scout quickview
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x78 pc=0x1017949e0]

goroutine 1 [running]:
github.com/google/go-containerregistry/pkg/v1.(*ConfigFile).Platform(...)
	/home/runner/go/pkg/mod/github.com/google/go-containerregistry@v0.19.1/pkg/v1/config.go:46
github.com/docker/scout-cli-plugin/internal/dockercli.(*Store).GetNewest(0x1400026cfb0, {0x102d4b4b0, 0x14000c251d0})
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/internal/dockercli/localstore.go:183 +0x9f0
github.com/docker/scout-cli-plugin/images.(*ImgService).GetNewestSource(0x14000f2cc00?, {0x102d4b4b0?, 0x14000c251d0?})
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/images/images.go:311 +0x34
github.com/docker/scout-cli-plugin/internal/commands/quickview.NewCmd.func2(0x0?, {0x0?, 0x0?, 0xaf03198e00000000?})
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/internal/commands/quickview/quickview.go:170 +0x610
github.com/docker/cli/cli-plugins/plugin.RunPlugin.func1.1.2(0x14000798f08, {0x104110c00, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/docker/cli@v26.1.3+incompatible/cli-plugins/plugin/plugin.go:69 +0x68
github.com/spf13/cobra.(*Command).execute(0x14000798f08, {0x14000510f50, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x140008bbb08)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/docker/cli/cli-plugins/plugin.RunPlugin(0x14000960000, 0x14000798008, {{0x101c82cc2, 0x5}, {0x101cac97f, 0xb}, {0x140013168b6, 0x6}, {0x101cb99b9, 0xc}, ...})
	/home/runner/go/pkg/mod/github.com/docker/cli@v26.1.3+incompatible/cli-plugins/plugin/plugin.go:84 +0x138
main.runPlugin(0x14000960000)
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/cmd/docker-scout/main.go:29 +0x104
main.main()
	/home/runner/work/scout-cli-plugin/scout-cli-plugin/cmd/docker-scout/main.go:53 +0x130

**Comment by mcandre** [comment]
Same problem with docker scout cves on RHEL.

**Comment by weishanlee** [comment]
When I run `docker scout quickview` on kubuntu24.04, my computer is running like a crazy (I can hear the sound) but I loose control of my computer from screen. The mouse is not working. The keyboard is not working, either. I am not sure if I have to wait longer or I just restart my computer with bruite-force.

**Comment by mcandre** [comment]
Update:

Docker Scout crashes with v1.13.0. Works fine with v1.12.0. Something is broken in the current release.
